apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ownke3lvn-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ownke3lvn-java-springboot-gitops